Vagrant.configure("2") do |config|

    config.vm.box = "sylabs/singularity-ce-3.8-ubuntu-bionic64"
  
    config.ssh.forward_agent = true
    config.ssh.forward_x11 = true
  
    config.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install xauth
      singularity exec --bind /vagrant /vagrant/elitpc_tpcreco_latest.sif cp -r /opt/soft/TPCReco/resources/. /vagrant   
      echo "cd /vagrant && singularity shell --bind /vagrant /vagrant/elitpc_tpcreco_latest.sif" >> /home/vagrant/.bashrc
      
      SHELL

end
